image:
  # image.parentRepository -- Docker registry to pull images from
  parentRepository: gcr.io/jenkinsxio

  repository: gcr.io/jenkinsxio/jx-preview

  # image.tag -- Docker images tag
  tag: 0.0.146

  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent

gcJobs:
  # gcJobs.schedule -- Cron expression to periodically garbage collect `Preview` resources; every 10 minutes by default
  schedule: "*/10 * * * *"

  # gcJobs.failedJobsHistoryLimit -- Drives the failed jobs history limit
  failedJobsHistoryLimit: 1

  # gcJobs.successfulJobsHistoryLimit -- Drives the successful jobs history limit
  successfulJobsHistoryLimit: 3

  # gcJobs.concurrencyPolicy -- Drives the job's concurrency policy
  concurrencyPolicy: Forbid

