{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-23T14:06:25Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: upgrade deps
    sha: 20e7b88d90f819251f6b4aa98d168ca31df2b6af
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: lets expose the preview URL, name and namespace

      in the `.jx/variables.sh` file so they are easy to use inside pipeline steps
    sha: ad3e47a294de0d3a9e81678641ed056e2674fb50
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 8de3c61f7e942846d06bc39c74044e1d1f27d152
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 5ff04de6328942cbb9b582cc9bead1c328de820d
  gitHttpUrl: https://github.com/jenkins-x/jx-preview
  gitOwner: jenkins-x
  gitRepository: jx-preview
  name: '{{ .Chart.Name }}'
  version: 0.0.160
status: {}
 
{{- end }}
